import type { Metadata } from "next";
import { Inter, Averia_Sans_Libre } from "next/font/google";

import SiteFooter from "@/components/shared/site-footer";
import SiteHeader from "@/components/shared/site-header";
import ScrollToTop from "@/components/shared/scroll-to-top";
import "./globals.css";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const averiaSansLibre = Averia_Sans_Libre({
  variable: "--font-averia-sans-libre",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interSans.variable} ${averiaSansLibre.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-gray-50">
        <ScrollToTop />
        {/* Header */}
        <SiteHeader />

        {/* Main Content */}
        <main className="flex-1">{children}</main>

        {/* Footer */}
        <SiteFooter />
      </body>
    </html>
  );
}
