import type { Metadata } from "next";
import { Geist, Geist_Mono, Oxanium } from "next/font/google";
import { useState } from "react";

import { createPageUrl, cn } from "@/lib/utils";

import "./globals.css";
import Link from "next/link";

const oxanium = Oxanium({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigationItems = [
  { title: "Home", url: createPageUrl("Home") },
  { title: "Portfolio", url: createPageUrl("Portfolio") },
  { title: "Services", url: createPageUrl("Services") },
  { title: "Pricing", url: createPageUrl("Pricing") },
  { title: "About", url: createPageUrl("About") },
  { title: "Blog", url: createPageUrl("Blog") },
  { title: "FAQ", url: createPageUrl("FAQ") },
  { title: "Contact", url: createPageUrl("Contact") },
];

export default function RootLayout({
  children,
  currentPageName,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", oxanium.variable)}
    >
      <body className="min-h-full flex flex-col">
        <div className="min-h-screen bg-gray-50">
          {/* Header */}
          <header className="bg-white neo-brutalist-border border-t-0 border-l-0 border-r-0 sticky top-0 z-50">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between items-center h-16">
                {/* Logo */}
                <Link
                  href={createPageUrl("Home")}
                  className="flex items-center"
                >
                  <div className="bg-blue-600 text-white px-4 py-2 neo-brutalist-border neo-brutalist-shadow-sm font-black text-xl transform -rotate-1">
                    MOGEN
                  </div>
                </Link>

                {/* Desktop Navigation */}
                <nav className="hidden md:flex items-center space-x-1">
                  {navigationItems.map((item) => (
                    <Link
                      key={item.title}
                      href={item.url}
                      className={`px-3 py-2 font-bold text-sm transition-all duration-200 ${
                        location.pathname === item.url
                          ? "bg-purple-500 text-white neo-brutalist-border neo-brutalist-shadow-sm transform -rotate-1"
                          : "hover:bg-lime-400 hover:neo-brutalist-border hover:neo-brutalist-shadow-sm hover:transform hover:-rotate-1"
                      }`}
                    >
                      {item.title.toUpperCase()}
                    </Link>
                  ))}
                </nav>

                {/* CTA Button */}
                <div className="hidden md:block">
                  <Link href={createPageUrl("Contact")}>
                    <Button className="bg-lime-400 text-black font-black neo-brutalist-border neo-brutalist-shadow hover:bg-lime-500 transform hover:scale-105 transition-all duration-200">
                      GET QUOTE
                    </Button>
                  </Link>
                </div>

                {/* Mobile menu button */}
                <button
                  onClick={() => setIsMenuOpen(!isMenuOpen)}
                  className="md:hidden p-2 neo-brutalist-border neo-brutalist-shadow bg-white"
                >
                  {isMenuOpen ? (
                    <X className="w-6 h-6" />
                  ) : (
                    <Menu className="w-6 h-6" />
                  )}
                </button>
              </div>
            </div>

            {/* Mobile Navigation */}
            {isMenuOpen && (
              <div className="md:hidden bg-white neo-brutalist-border border-t-4">
                <div className="px-2 pt-2 pb-3 space-y-1">
                  {navigationItems.map((item) => (
                    <Link
                      key={item.title}
                      href={item.url}
                      onClick={() => setIsMenuOpen(false)}
                      className={`block px-3 py-2 text-base font-bold ${
                        location.pathname === item.url
                          ? "bg-purple-500 text-white neo-brutalist-border neo-brutalist-shadow-sm"
                          : "hover:bg-lime-400 hover:neo-brutalist-border hover:neo-brutalist-shadow-sm"
                      }`}
                    >
                      {item.title.toUpperCase()}
                    </Link>
                  ))}
                  <Link
                    href={createPageUrl("Contact")}
                    onClick={() => setIsMenuOpen(false)}
                    className="block w-full mt-4"
                  >
                    <Button className="w-full bg-lime-400 text-black font-black neo-brutalist-border neo-brutalist-shadow">
                      GET QUOTE
                    </Button>
                  </Link>
                </div>
              </div>
            )}
          </header>

          {/* Main Content */}
          <main className="flex-1">{children}</main>

          {/* Footer */}
          <footer className="bg-black text-white mt-16">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                <div className="col-span-1 md:col-span-2">
                  <div className="bg-blue-600 text-white px-4 py-2 neo-brutalist-border border-white neo-brutalist-shadow font-black text-xl inline-block transform rotate-1 mb-4">
                    MOGEN PTY LTD
                  </div>
                  <p className="text-gray-300 text-lg font-bold mb-4">
                    BOLD WEB SOLUTIONS FOR LOCAL BUSINESSES
                  </p>
                  <p className="text-gray-400">
                    Serving Maboloka, Soshanguve, and neighbouring regions with
                    affordable, world-class web development and brand identity
                    services.
                  </p>
                </div>

                <div>
                  <h3 className="font-black text-lg mb-4 text-lime-400">
                    QUICK LINKS
                  </h3>
                  <ul className="space-y-2">
                    <li>
                      <Link
                        href={createPageUrl("Services")}
                        className="hover:text-lime-400 font-bold"
                      >
                        SERVICES
                      </Link>
                    </li>
                    <li>
                      <Link
                        href={createPageUrl("Portfolio")}
                        className="hover:text-lime-400 font-bold"
                      >
                        PORTFOLIO
                      </Link>
                    </li>
                    <li>
                      <Link
                        tohref={createPageUrl("Pricing")}
                        className="hover:text-lime-400 font-bold"
                      >
                        PRICING
                      </Link>
                    </li>
                    <li>
                      <Link
                        href={createPageUrl("Blog")}
                        className="hover:text-lime-400 font-bold"
                      >
                        BLOG
                      </Link>
                    </li>
                    <li>
                      <Link
                        href={createPageUrl("FAQ")}
                        className="hover:text-lime-400 font-bold"
                      >
                        FAQ
                      </Link>
                    </li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-black text-lg mb-4 text-purple-500">
                    CONTACT
                  </h3>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <Phone className="w-4 h-4 text-lime-400" />
                      <span className="font-bold">+27 (0)71.863.1884</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Mail className="w-4 h-4 text-lime-400" />
                      <span className="font-bold">info@mogen.co.za</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="border-t-4 border-white mt-8 pt-8 text-center">
                <p className="text-gray-400 font-bold">
                  © 2025-{new Date().getFullYear()} MOGEN PTY LTD. ALL RIGHTS
                  RESERVED.
                </p>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
